name: esp32_relay_app
description: ESP32 Relay Control App with MQTT & Energy Monitoring
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^9.2.0
  flutter_svg: ^2.0.0
  charts_flutter: ^0.14.0
  http: ^0.15.0
  shared_preferences: ^2.2.0
  provider: ^6.1.1
  firebase_auth: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
